RootNode:
    BaseYaml: ../../CommonForms/PetraForm.yaml
    FormTitle: Browse Long-Term Applications
    Namespace: Ict.Petra.Client.MPersonnel.Gui
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.ApplicationTDS
    MasterTable: PmGeneralApplication
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data, Ict.Petra.Shared.MPersonnel.Personnel.Validation]
    FormType: browse
    Template: windowFind
    TemplateParameters:
        INITMANUALCODE: InitGridManually();
    WindowWidth: 600
    WindowHeight: 600
    Actions:
        actSearch: {ActionClick=Search_Click}
        actClear: {ActionClick=Clear_Click}
        actEditApplication: {Label=Edit Application, ActionClick=EditApplication}
        actCreateExtract: {ActionClick=CreateExtract_Click}
        actSelectStatuses: {ActionClick=SelectStatuses_Click}
    Controls:
        pnlContent:
            Controls: [pnlControls, pnlGrid]
            Dock: Fill
        pnlControls:
            Dock: Top
            Height: 220
            Controls: [grpApplicationDetails, rgrApplicationStatusFilter]
        grpApplicationDetails:
            Stretch: horizontally
            Label: Search
            Controls:
                Row0: [txtTargetFieldKey]
                Row1: [txtPlacementPersonKey]
                Row2: [btnSearch, btnClear]
        rgrApplicationStatusFilter:
            Stretch: horizontally
            Controls: [rbtAll, rbtGeneral, rbtDetailed]
            ControlsOrientation: vertical
            ColWidths: [0=Fixed:190]
        pnlGrid:
            Dock: Fill
            Controls: [pnlButtons, grdApplications]
        pnlButtons:
            Dock: Bottom
            Controls: [btnEditApplication, btnCreateExtract]
            ControlsOrientation: horizontal
        grdApplications:
            Dock: Fill
            Columns: [PPartner.PartnerShortName, PmGeneralApplication.GenApplicationStatus, PmYearProgramApplication.YpAppDate, PmGeneralApplication.GenAppPossSrvUnitKey]
            CustomColumns:
                PPartner.PartnerShortName: {Label=Attendee Name}
                PmGeneralApplication.GenAppPossSrvUnitKey: {Label=Target Field}
                PmYearProgramApplication.YpAppDate: {Label=Date Entered, Type=DateTime}

        rbtAll:
            Height: 15
            Padding: 5,5,0,0
            ActionClick: FilterChange
        rbtGeneral:
            Controls: [chkAccepted, chkCancelled, chkHold, chkEnquiry, chkRejected]
            ControlsOrientation: horizontal
            Height: 15
            Padding: 5,17,0,0
            ActionClick: FilterChange
        rbtDetailed:
            Controls: [btnSelectDetailedStatuses, txtDetailedStatuses]
            ControlsOrientation: horizontal
            Padding: 5,10,0,0
            Height: 15
            ActionClick: FilterChange

        txtTargetFieldKey:
            Label: Target Field
            Type: PartnerKey
            PartnerClass: UNIT
            Stretch: horizontally
        txtPlacementPersonKey:
            Label: Placement Person
            Type: PartnerKey
            PartnerClass: PERSON
        chkAccepted:
            CheckBoxAttachedLabel: right
            Padding: 0,7,0,0
            ActionClick: FilterChange
            Checked: true
        chkCancelled:
            CheckBoxAttachedLabel: right
            Padding: 0,7,0,0
            ActionClick: FilterChange
        chkHold:
            CheckBoxAttachedLabel: right
            Padding: 0,7,0,0
            ActionClick: FilterChange
        chkEnquiry:
            CheckBoxAttachedLabel: right
            Padding: 0,7,0,0
            ActionClick: FilterChange
        chkRejected:
            CheckBoxAttachedLabel: right
            Padding: 0,7,0,0
            ActionClick: FilterChange
        txtDetailedStatuses: 
            ReadOnly: true
            BorderStyle: None
            Stretch: horizontally
            NoLabel: true
            Padding: 0,-1,0,0
            Width: 275

        btnSearch:
            Action: actSearch
        btnClear:
            Action: actClear
            Aligh: right
        btnEditApplication:
            Action: actEditApplication
            Enabled: false
        btnCreateExtract:
            Action: actCreateExtract
        btnSelectDetailedStatuses:
            Height: 25
            Padding: 0,-1,0,0
            Label: Select Detailed Statuses...
            Action: actSelectStatuses