RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MPartner.Gui
    DatasetType: Ict.Petra.Shared.MPersonnel.Personnel.Data.IndividualDataTDS
    DetailTable: PmGeneralApplication
    UsingNamespaces: [Ict.Petra.Shared.MPersonnel.Personnel.Data,Ict.Petra.Shared.MPersonnel.Personnel.Validation]
    FormType: edit
    Template: controlMaintainTable
    Actions:
        actNewShortTerm: {ActionClick=NewRowShortTermApp, Image=New_Record.ico}
        actNewLongTerm: {ActionClick=NewRowLongTermApp, Image=New_Record.ico}
        actDelete: {Label=&Delete, SkipReferenceCheck=true, ActionClick=DeleteRecord}
    Controls:
        pnlContent:
            Dock: Fill
            Controls: [sptApplications]
        sptApplications:
            SplitterOrientation: Horizontal
            SplitterDistance: 240
            Height: 600
            Dock: Fill
            BackColor: System.Drawing.SystemColors.ControlDark
            Panel1: pnlDetailGrid
            Panel2: pnlDetails
        pnlDetailGrid:
            Dock: Fill
            BackColor: System.Drawing.SystemColors.Control
            Controls:
                Row0: [pnlDetailButtons, grdDetails]
        pnlDetailButtons:
            Dock: Bottom
            Controls: [btnNewShortTerm, btnNewLongTerm, btnDelete]
            ControlsOrientation: horizontal
        btnNewShortTerm: {Label=New (for Event), Width=120, Action=actNewShortTerm}
        btnNewLongTerm: {Label=New (for Field), Width=120, Action=actNewLongTerm}
        btnDelete: {Action=actDelete, Width=120}
        grdDetails:
            Dock: Fill
            Columns: []
            AutoFindColumn: 2
            ActionFocusRow: FocusedRowChanged       
        pnlDetails:
            Dock: Fill
            BackColor: System.Drawing.SystemColors.Control
            Controls: [pnlApplicationEvent, pnlApplicationField]
            Height: 350
            
        pnlApplicationEvent:
            Dock: Fill
            Controls: [ucoApplicationEvent]
        pnlApplicationField:
            Dock: Fill
            Controls: [ucoApplicationField]


        ucoApplicationEvent:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_Application_Event
        ucoApplicationField:
            Dock: Fill
            Type: Ict.Petra.Client.MPartner.Gui.TUC_Application_Field
            