RootNode:
    BaseClass: UserControl
    UtilObjectClass: TFrmPetraReportingUtils
    Namespace: Ict.Petra.Client.MReporting.Gui.MFinance
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    FormType: edit
    Template: usercontrolUnbound
    UsingNamespaces: [Ict.Common.Data]
    Actions:
        actUnselectAllCostCentres:
            ActionClick: UnselectAllCostCentres
        actUnselectAllAccountCodes:
            ActionClick: UnselectAllAccountCodes
        actSelectAllReportingCostCentres:
            ActionClick: SelectAllReportingCostCentres
        actAllExpenseAccounts:
            ActionClick: SelectAllExpenseAccounts
    Controls:
        pnlContent:
            Controls: [rgrAccountCodes, rgrCostCentre]
            Dock: Fill
            
        rgrAccountCodes: 
            ParameterName: param_account_codes
            Controls: [rbtAllAccounts, rbtAccountRange, rbtAccountFromList]
            Label: Select Account Codes
            Dock: Top
        rbtAllAccounts:
        rbtAccountRange:
            Label: Select Range
            Controls: [cmbFromAccountCode, cmbToAccountCode]
        rbtAccountFromList:
            Stretch: horizontally
            Label: From List
            Controls: [pnlAccountFromList]
            OnChange: AccountChanged
        pnlAccountFromList:
            Stretch: horizontally
            Controls: 
                Row0: [clbAccountCodes, btnUnselectAllAccountCodes]
                Row1: [btnAllExpenseAccounts]
            
        rgrCostCentre: 
            ParameterName: param_costcentreoptions
            Controls: [rbtAllCostCentres, rbtCostCentreRange, rbtCostCentreFromList]
            Label: Select Cost Centre Codes
            Dock: Top
        rbtAllCostCentres:
        rbtCostCentreRange:
            Label: Select Range
            Controls: [cmbFromCostCentre, cmbToCostCentre]
        rbtCostCentreFromList:
            Label: From List
            Controls: [pnlCostCentreFromList]
            OnChange: CostCentreChanged
        pnlCostCentreFromList:
            Stretch: horizontally
            Controls: 
                Row0: [clbCostCentres, btnUnselectAllCostCentres]
                Row1: [cmbSummaryCostCentres]
                Row2: [btnSelectAllReportingCostCentres]
        
        clbAccountCodes: 
            List: UserDefinedList
            AutoFindColumn: 2
            NoLabel:true
            Width: 360
        btnUnselectAllAccountCodes:
            Label: Unselect All
            Action: actUnselectAllAccountCodes
            Enabled: false
        btnAllExpenseAccounts:
            Action: actAllExpenseAccounts
            Enabled: false
        cmbFromAccountCode:
            List: UserDefinedList
            Label: From
            Enabled: false
        cmbToAccountCode:
            List: UserDefinedList
            Label: To
            Enabled: false
        cmbFromCostCentre:
            List: UserDefinedList
            Label: From
            Enabled: false
        cmbToCostCentre:
            List: UserDefinedList
            Label: To
            Enabled: false
        cmbSummaryCostCentres:
            ColSpan: 2
            List: UserDefinedList
            Label: Summary Cost Centre
            OnChange: SummaryCostCentresChanged
            Enabled: false

        clbCostCentres:
            List: UserDefinedList
            AutoFindColumn: 2
            NoLabel:true
            Width: 360
        btnUnselectAllCostCentres: 
            Label: Unselect All
            Action: actUnselectAllCostCentres
            Enabled: false
        btnSelectAllReportingCostCentres:
            Label: Add summary's reporting cost centres
            Enabled: false