RootNode:
    BaseClass: UserControl
    UtilObjectClass: TFrmPetraReportingUtils
    Namespace: Ict.Petra.Client.MReporting.Gui.MFinance
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    FormType: edit
    Template: usercontrolUnbound
    Actions:
        actUnselectAll:
            ActionClick: UnselectAll
    Controls:
        pnlContent:
            Controls: [grpCostCentreSelection, grpCostCentreOptions]
            Dock: Fill
        grpCostCentreSelection:
            Width: 650
            ParameterName: param_costcentreoptions
            Controls: [rbtSelectedCostCentres, rbtAllCostCentres, rbtAllActiveCostCentres, rbtAccountLevel, chkExcludeInactiveCostCentres]
        grpCostCentreOptions:
            Width: 650
            Controls: [pnlAutoEmail, chkCostCentreBreakdown, rgrDepth]
        rbtSelectedCostCentres:
            Controls: [clbCostCentres, btnUnselectAllCostCentres]
            ControlsOrientation: horizontal
            OnChange: rbtSelectedCostCentresChanged
        rbtAllCostCentres:
        rbtAllActiveCostCentres:
        rbtAccountLevel:
        chkExcludeInactiveCostCentres:
            Label: Exclude inactive Cost Centres
            CheckBoxAttachedLabel: right
            ParameterName: param_ExcludeInactiveCostCentres
            OnChange: chkExcludeCostCentresChanged
        clbCostCentres: 
            List: UserDefinedList
            NoLabel:true
            ParameterName: param_cost_centre_codes
            Width: 365
            Stretch: vertically
        btnUnselectAllCostCentres: 
            Label: Unselect All
            Action: actUnselectAll
        pnlAutoEmail:
            Controls: [chkPaginate,chkAutoEmail]
            ControlsOrientation: horizontal
        chkPaginate:
            ParameterName: param_paginate
        chkAutoEmail:
            ParameterName: param_auto_email
        chkCostCentreBreakdown: 
            ParameterName: param_cost_centre_breakdown
            Tooltip: group not by costcentre but by account
            CheckBoxAttachedLabel: right
        rgrDepth:
            ParameterName: param_depth
            ControlsOrientation: horizontal
            OptionalValues: [Summary, Standard, Detail]
            
     