RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MFinance.Gui.Setup   
    UsingNamespaces: [Ict.Petra.Shared.MFinance.Account.Data, Ict.Petra.Shared.MFinance.GL.Data, Ict.Petra.Shared.MFinance.Account.Validation]
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    MasterTable: ALedger
    FormType: edit
    Template: usercontrol
    WindowWidth: 565
    WindowHeight: 565
    Actions:
    Controls:
        pnlContent:
            Dock: Fill
            Controls: [grpCurrencies, grpAccountingPeriods, grpMiscellaneousFlags, grpDataRetention]
        grpCurrencies: {Label=Currencies, Width=550, Stretch=horizontally}
            Controls: [cmbBaseCurrency, cmbIntlCurrency]
        grpAccountingPeriods: {Label=Accounting Periods, Width=550, Stretch=horizontally}
            Controls: [rgrCalendarModeRadio, nudNumberOfAccountingPeriods, dtpFinancialYearStartDate, nudCurrentPeriod, btnViewCalendar, nudNumberFwdPostingPeriods]
        grpMiscellaneousFlags: {Label=Miscellaneous, Width=550, Stretch=horizontally}
            Controls: [chkSuspenseAccountFlag, chkBudgetControlFlag]
        grpDataRetention: {Label=Data Retention, Width=550, Stretch=horizontally}
            Controls: [nudActualsDataRetention, nudGiftDataRetention]
            
        rgrCalendarModeRadio:
            Controls: [rbtMonthly, rbtNonMonthly]
            NoLabel: true
            BorderVisible: false
            ControlsOrientation: horizontal
        rbtMonthly:
            Label: Monthly
            OnChange: CalendarModeChanged
            ParameterValue: Monthly
        rbtNonMonthly:
            Label: Non-monthly
            OnChange: CalendarModeChanged
            ParameterValue: Non-monthly
        
        cmbBaseCurrency: {List=CurrencyCodeList}
        cmbIntlCurrency: {List=CurrencyCodeList}
        nudNumberOfAccountingPeriods: {Label=Number of Periods, Width=60, Validation=true}
        nudCurrentPeriod: {Label=Current Period, Width=60, Validation=true}
        btnViewCalendar: {Label=View Calendar, ActionClick=OnBtnCalendar}
        dtpFinancialYearStartDate: {Label=First Day of the Financial Year, Align=bottom}
        chkSuspenseAccountFlag: {Label=Allow use of suspense accounts, CheckBoxAttachedLabel=right, Validation=true}
        chkBudgetControlFlag: {Label=Budget control, CheckBoxAttachedLabel=right}
        nudNumberFwdPostingPeriods: {Label=Forward Posting Periods, Width=60, Validation=true}
        nudActualsDataRetention: {Label=Actuals Data Retention Period, Width=60}
        #nudBudgetDataRetention: {Label=Budget Data Retention Period}
        nudGiftDataRetention: {Label=Gift Data Retention Period, Width=60}
