RootNode:
    BaseClass: System.Windows.Forms.UserControl
    UtilObjectClass: TFrmPetraEditUtils
    Namespace: Ict.Petra.Client.MFinance.Gui.Setup
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    DetailTable: AFreeformAnalysis
    UsingNamespaces: [Ict.Petra.Shared.MFinance.Account.Data,Ict.Petra.Shared.MFinance.Account.Validation]
    FormType: edit
    Template: controlMaintainTable
    Actions:
        actNew: {Label=&New, ActionClick=NewRow}
        actDelete: {Label=&Delete, ActionClick=DeleteRecord}      
    Controls:
        pnlContent:
            Controls: [pnlDetailTop, pnlGrid, pnlDetails]
            Dock: Fill
        pnlGrid:
            Dock: Fill
            Controls: [pnlFilterAndFind, pnlButtons, grdDetails]
        pnlFilterAndFind:
            ExpandedWidth: 175
            FilterControls: [txtDetailAnalysisValue, chkDetailActive]
            FindControls: [txtDetailAnalysisValue]
        pnlButtons:
            Dock: Bottom
            Controls: [btnNew, btnDelete]
            ControlsOrientation: horizontal
        btnNew:
            Label: &New Analysis Value
            Tooltip: Click to create a new Analysis Value.                
            Action: actNew
            Width: 160
        btnDelete:
            Label: &Delete Analysis Value
            Tooltip: Click to delete the highlighted Analysis Value(s).                        
            Action: actDelete
            Width: 160
        grdDetails:
            Tooltip: Use the mouse or navigation keys to select an Analysis Value to view or edit.                
            Dock: Fill
            Columns: [AFreeformAnalysis.AnalysisValue, AFreeformAnalysis.Active]
            SortOrder: AFreeformAnalysis.AnalysisValue ASC
            ActionFocusRow: FocusedRowChanged
        pnlDetails:
            Height: 70
            Dock: Bottom
            Controls:
                Row0: [txtDetailAnalysisValue]
                Row1: [chkDetailActive]
        txtDetailAnalysisValue: {Label=&Value, Width=400}
        chkDetailActive: {Label=A&ctive}
        pnlDetailTop:
            Dock: Top
            Controls: [txtHeaderLedgerNumber]
        txtHeaderLedgerNumber: {Label=Values for this Type and Ledger Number,ReadOnly=true}